// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Database.API.Models
{
    public partial class Profile
    {
        public string UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string StoreName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StoreOwner { get; set; }
        public string Position { get; set; }
    }
}