// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Database.API.Models
{
    public partial class Store
    {
        public string StoreId { get; set; }
        public string StoreName { get; set; }
        public string Location { get; set; }
        public string NameOwner { get; set; }
    }
}