// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Database.API.Models
{
    public partial class TypeProduct
    {
        public TypeProduct()
        {
            Product = new HashSet<Product>();
        }

        public string TypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}