// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Database.API.Models
{
    public partial class UserDb
    {
        public string UserId { get; set; }
        public string Username { get; set; }
        public int? Password { get; set; }
    }
}